# Generated by Django 3.2.4 on 2023-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Speelteam',
                'verbose_name_plural': 'Speelteams',
            },
        ),
        migrations.CreateModel(
            name='ScoreTableEntryForRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Positie')),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Score tabel regel',
                'verbose_name_plural': 'Score tabel regels',
                'ordering': ('round', 'position'),
            },
        ),
        migrations.CreateModel(
            name='StageScoreForParticipantTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_for_stage', models.IntegerField(default=0, verbose_name='Totaal voor etappe')),
                ('accumulated_score', models.IntegerField(default=0, verbose_name='Geaccumuleerde score')),
            ],
            options={
                'verbose_name': 'Etappe score voor team',
                'verbose_name_plural': 'Etappe scores voor teams',
                'ordering': ('stage__round', 'stage'),
            },
        ),
        migrations.CreateModel(
            name='StageScoreForRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Positie')),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Score voor renner',
                'verbose_name_plural': 'Score voor renners',
                'ordering': ('stage__round', 'stage'),
            },
        ),
    ]
