# Generated by Django 3.2.4 on 2023-07-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagescoreforrider',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_for_stages', to='races.riderforteam', verbose_name='Renner'),
        ),
        migrations.AddField(
            model_name='stagescoreforrider',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_for_riders', to='races.stageday', verbose_name='Etappe'),
        ),
        migrations.AddField(
            model_name='stagescoreforparticipantteam',
            name='participant_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_for_stages', to='games.participantteam', verbose_name='Team voor deelnemer'),
        ),
        migrations.AddField(
            model_name='stagescoreforparticipantteam',
            name='rider_stage_scores',
            field=models.ManyToManyField(blank=True, to='games.StageScoreForRider'),
        ),
        migrations.AddField(
            model_name='stagescoreforparticipantteam',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_for_participants', to='races.stageday', verbose_name='Etappe'),
        ),
        migrations.AddField(
            model_name='scoretableentryforround',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.round', verbose_name='Ronde'),
        ),
        migrations.AddField(
            model_name='participantteam',
            name='riders',
            field=models.ManyToManyField(blank=True, to='races.RiderForTeam', verbose_name='Renners'),
        ),
        migrations.AddField(
            model_name='participantteam',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.round', verbose_name='Ronde'),
        ),
        migrations.AddField(
            model_name='participantteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker'),
        ),
        migrations.AddConstraint(
            model_name='stagescoreforparticipantteam',
            constraint=models.UniqueConstraint(fields=('participant_team', 'stage'), name='unique score for participant and stage'),
        ),
        migrations.AlterUniqueTogether(
            name='participantteam',
            unique_together={('user', 'round')},
        ),
    ]
