# Generated by Django 3.2.4 on 2023-07-15 14:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_races.day_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Ronde dag',
                'verbose_name_plural': 'Ronde dagen',
                'ordering': ('round', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(max_length=100, verbose_name='Achternaam')),
                ('birth_date', models.DateField(verbose_name='Geboortedatum')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Renner',
                'verbose_name_plural': 'Renners',
            },
        ),
        migrations.CreateModel(
            name='RiderForTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.BooleanField(default=False, verbose_name='Kopman')),
                ('number', models.IntegerField(verbose_name='Rugnummer')),
                ('sprint_quality', models.IntegerField(choices=[(1, 'Weinig'), (2, 'Gemiddeld'), (3, 'Veel')], verbose_name='Sprint kwaliteit')),
                ('climb_quality', models.IntegerField(choices=[(1, 'Weinig'), (2, 'Gemiddeld'), (3, 'Veel')], verbose_name='Klim kwaliteit')),
                ('attack_quality', models.IntegerField(choices=[(1, 'Weinig'), (2, 'Gemiddeld'), (3, 'Veel')], verbose_name='Aanval kwaliteit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Renner nog in koers')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.rider', verbose_name='Renner')),
            ],
            options={
                'verbose_name': 'Renner voor team',
                'verbose_name_plural': 'Renners voor team',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Einddatum')),
                ('type', models.CharField(choices=[('tour_de_france', 'Tour de France'), ('giro_d_italia', "Giro d'Italia"), ('vuelta_a_espana', 'Vuelta a España')], max_length=15, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Ronde',
                'verbose_name_plural': 'Rondes',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('is_active', models.BooleanField(default=True, verbose_name='Team actief')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='RestDay',
            fields=[
                ('day_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='races.day')),
                ('number', models.IntegerField(verbose_name='Rustdagnummer')),
            ],
            options={
                'verbose_name': 'Rustdag',
                'verbose_name_plural': 'Rustdagen',
            },
            bases=('races.day',),
        ),
        migrations.CreateModel(
            name='StageDay',
            fields=[
                ('day_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='races.day')),
                ('number', models.IntegerField(verbose_name='Etappe nummer')),
                ('start_city', models.CharField(max_length=100, verbose_name='Start stad')),
                ('end_city', models.CharField(max_length=100, verbose_name='Eind stad')),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4, max_length=7, verbose_name='Afstand')),
                ('stage_type', models.CharField(choices=[('mountain', 'Bergen'), ('individual-time-trial', 'Individuele tijdrit'), ('team-time-trial', 'Ploegen tijdrit'), ('hilly', 'Heuvelachtig'), ('flat', 'Plat')], max_length=32, verbose_name='Etappe type')),
            ],
            options={
                'verbose_name': 'Etappe',
                'verbose_name_plural': 'Etappes',
                'ordering': ('round', 'number'),
            },
            bases=('races.day',),
        ),
        migrations.CreateModel(
            name='TeamForRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riders', models.ManyToManyField(through='races.RiderForTeam', to='races.Rider')),
                ('round', models.ForeignKey(help_text='Geef hier de ronde op', on_delete=django.db.models.deletion.PROTECT, to='races.round', verbose_name='Ronde')),
                ('team', models.ForeignKey(help_text='Geef hier het team op', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='races.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team voor ronde',
                'verbose_name_plural': 'Teams voor ronde',
            },
        ),
        migrations.AddField(
            model_name='riderforteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.teamforround', verbose_name='Team voor ronde'),
        ),
        migrations.AddField(
            model_name='day',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='races.round', verbose_name='Ronde'),
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Positie')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.riderforteam', verbose_name='Renner')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.stageday', verbose_name='Etappe')),
            ],
            options={
                'verbose_name': 'Etappe resultaat',
                'verbose_name_plural': 'Etappe resultaten',
                'ordering': ('stage__round', 'stage'),
            },
        ),
        migrations.AddConstraint(
            model_name='riderforteam',
            constraint=models.UniqueConstraint(fields=('team', 'rider'), name='unique rider for team'),
        ),
    ]
