# Generated by Django 5.2.3 on 2025-06-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
