# Generated by Django 5.2.3 on 2025-06-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_round_year_alter_day_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('tour-de-france', 'Tour de France'), ('giro-d-italia', "Giro d'Italia"), ('vuelta-a-espana', 'Vuelta a España')], max_length=15, verbose_name='Type'),
        ),
    ]
