# Generated by Django 5.2.3 on 2025-06-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_alter_round_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderforteam',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='teamforround',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
