# Generated by Django 5.2.3 on 2025-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_riderforteam_photo_teamforround_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderforteam',
            name='attack_quality',
            field=models.IntegerField(blank=True, choices=[(1, 'Weinig'), (2, 'Gemiddeld'), (3, 'Veel')], null=True, verbose_name='Aanval kwaliteit'),
        ),
        migrations.AlterField(
            model_name='riderforteam',
            name='climb_quality',
            field=models.IntegerField(blank=True, choices=[(1, 'Weinig'), (2, 'Gemiddeld'), (3, 'Veel')], null=True, verbose_name='Klim kwaliteit'),
        ),
        migrations.AlterField(
            model_name='riderforteam',
            name='sprint_quality',
            field=models.IntegerField(blank=True, choices=[(1, 'Weinig'), (2, 'Gemiddeld'), (3, 'Veel')], null=True, verbose_name='Sprint kwaliteit'),
        ),
    ]
