# Generated by Django 5.2.3 on 2025-07-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_alter_riderforteam_attack_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamforround',
            options={'ordering': ['order'], 'verbose_name': 'Team voor ronde', 'verbose_name_plural': 'Teams voor ronde'},
        ),
    ]
