# Generated by Django 5.2.3 on 2025-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderforparticipantteam',
            options={'ordering': ('position',)},
        ),
        migrations.RemoveField(
            model_name='riderforparticipantteam',
            name='added_at',
        ),
        migrations.AddField(
            model_name='riderforparticipantteam',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
