version: '3.7'

services:
  web:
    image: tourdefrance
    container_name: tourdefrance-web
    build:
      context: ./..
      dockerfile: _docker/Dockerfile
    command: >
      bash -c "python manage.py migrate && \
               python manage.py runserver 0.0.0.0:8000"
#    command: ls -la
    # Set the UID en GID env vars in your docker-compose config or in bashrc profiles:
    # https://blog.giovannidemizio.eu/2021/05/24/how-to-set-user-and-group-in-docker-compose/
#    user: "${UID}:${GID}"
    volumes:
      - ./../:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: tourdefrance-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./../backups:/var/backups
    environment:
      - POSTGRES_USER=tourdefrance
      - POSTGRES_PASSWORD=tourdefrance
      - POSTGRES_DB=tourdefrance_db
    ports:
      - 15432:5432

volumes:
  postgres_data:
